'use client';

import type { SettingsIconKey } from '@/lib/settings/registry';
import {
  BadgeCheck,
  BarChart3,
  Bell,
  Boxes,
  Brain,
  Brush,
  Building2,
  CheckSquare,
  Database,
  Download,
  FileText,
  HardHat,
  Inbox,
  Info,
  Landmark,
  LifeBuoy,
  Lock,
  Mail,
  MessageCircle,
  Mic2,
  Palette,
  Phone,
  Plane,
  Plug,
  Receipt,
  Ruler,
  Scale,
  ScrollText,
  Send,
  Server,
  ShieldCheck,
  Sparkles,
  User,
  Users,
  UsersRound,
  Wallet,
  Workflow,
  Wrench,
} from 'lucide-react';
import type { ComponentType } from 'react';

/** El icono de cada clave del registro. El registro es texto para poder viajar de servidor a cliente. */
export const SETTINGS_ICONS: Record<SettingsIconKey, ComponentType<{ className?: string }>> = {
  user: User,
  palette: Palette,
  bell: Bell,
  mic: Mic2,
  brain: Brain,
  mail: Mail,
  inbox: Inbox,
  lock: Lock,
  download: Download,
  building: Building2,
  brush: Brush,
  boxes: Boxes,
  users: Users,
  'users-round': UsersRound,
  'badge-check': BadgeCheck,
  shield: ShieldCheck,
  chart: BarChart3,
  scroll: ScrollText,
  receipt: Receipt,
  landmark: Landmark,
  wallet: Wallet,
  'hard-hat': HardHat,
  scale: Scale,
  plane: Plane,
  'check-square': CheckSquare,
  workflow: Workflow,
  ruler: Ruler,
  message: MessageCircle,
  sparkles: Sparkles,
  database: Database,
  phone: Phone,
  plug: Plug,
  wrench: Wrench,
  server: Server,
  'life-buoy': LifeBuoy,
  send: Send,
  'file-text': FileText,
  info: Info,
};
