-- better-auth tables + decouple public.users from Supabase Auth
--
-- Background:
--   We are switching SSO from Supabase Auth to better-auth (Google SSO).
--   better-auth manages its own user/session/account/verification tables
--   (prefixed `ba_` to avoid the reserved word `user`). The pre-existing
--   `public.users` table previously FK'd to `auth.users(id)` with no default;
--   we now decouple it (linking by email instead) and drop the Supabase Auth
--   signup trigger introduced in 0009.

-- ----------------------------------------------------------------------
-- 1. Decouple public.users from auth.users
-- ----------------------------------------------------------------------

-- Drop the old Supabase Auth signup trigger + function (defined in 0009).
drop trigger if exists on_auth_user_created on auth.users;
drop function if exists public.handle_new_auth_user();

-- Drop the FK constraint on public.users.id -> auth.users.id (anonymous name
-- gets autogenerated by Postgres; use dynamic lookup so we don't depend on it).
do $$
declare
  cname text;
begin
  for cname in
    select conname
    from pg_constraint
    where conrelid = 'public.users'::regclass
      and contype = 'f'
  loop
    execute format('alter table public.users drop constraint %I', cname);
  end loop;
end$$;

-- public.users.id can now be self-generated; we'll insert rows ourselves
-- from better-auth's after-user-create hook, linking by email.
alter table public.users alter column id set default gen_random_uuid();

-- ----------------------------------------------------------------------
-- 2. better-auth tables
-- ----------------------------------------------------------------------
-- Column names use quoted camelCase to match better-auth's default Kysely
-- adapter behavior (when passing a pg Pool directly, casing defaults to
-- "camel"). Table names are configured via `user.modelName = 'ba_user'`,
-- etc., in lib/auth.ts.

create table if not exists public.ba_user (
  id text primary key,
  name text not null,
  email text not null unique,
  "emailVerified" boolean not null default false,
  image text,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table if not exists public.ba_session (
  id text primary key,
  "expiresAt" timestamptz not null,
  token text not null unique,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  "ipAddress" text,
  "userAgent" text,
  "userId" text not null references public.ba_user(id) on delete cascade
);

create table if not exists public.ba_account (
  id text primary key,
  "accountId" text not null,
  "providerId" text not null,
  "userId" text not null references public.ba_user(id) on delete cascade,
  "accessToken" text,
  "refreshToken" text,
  "idToken" text,
  "accessTokenExpiresAt" timestamptz,
  "refreshTokenExpiresAt" timestamptz,
  scope text,
  password text,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table if not exists public.ba_verification (
  id text primary key,
  identifier text not null,
  value text not null,
  "expiresAt" timestamptz not null,
  "createdAt" timestamptz,
  "updatedAt" timestamptz
);

-- All better-auth tables are service-role only from the DB side. better-auth
-- itself talks to the DB via the SUPABASE_DB_URL connection (service role
-- bypasses RLS), so client / anon callers must never read these directly.
alter table public.ba_user enable row level security;
alter table public.ba_session enable row level security;
alter table public.ba_account enable row level security;
alter table public.ba_verification enable row level security;

create policy ba_no_client_access_user on public.ba_user for all using (false) with check (false);
create policy ba_no_client_access_session on public.ba_session for all using (false) with check (false);
create policy ba_no_client_access_account on public.ba_account for all using (false) with check (false);
create policy ba_no_client_access_verification on public.ba_verification for all using (false) with check (false);

-- ----------------------------------------------------------------------
-- 3. RLS implications of moving off Supabase Auth
-- ----------------------------------------------------------------------
-- IMPORTANT: All policies in 0008_rls.sql key off `auth.uid()`, which only
-- returns a non-NULL value when the caller authenticated via Supabase Auth.
-- Since SSO is now handled by better-auth, `auth.uid()` returns NULL for
-- every request, and those policies effectively evaluate to `false`.
--
-- Mitigation for MVP: ALL data access from the API layer MUST go through
-- the service-role client (`getSupabaseServiceClient()` in
-- `apps/web/lib/supabase/service.ts`), which bypasses RLS. The session
-- guard is enforced in application code via `requireSession()`.
--
-- Defense-in-depth at the DB level is intentionally deferred. A future
-- migration may either:
--   (a) Replace `auth.uid()` checks with `current_setting('app.user_id')`
--       set via `SET LOCAL` from the API layer, or
--   (b) Move data access into security-definer SQL functions with explicit
--       user-id parameters.
--
-- Until that migration lands, NEVER use the anon-key (or any non-service)
-- Postgres client to read `public.*` tables from client code.
